[package]
name = "shrimply-manim-cuda"
version = "0.1.0"
edition = "2024"

[target.'cfg(any(target_os = "linux", windows))'.dependencies]
shrimply-gpu-vulkan.workspace = true
hashbrown.workspace = true
shrimply-gpu-cuda.workspace = true
shrimply-profiling = { workspace = true }
shrimply-gpu-cuda-memory = { workspace = true }
shrimply-visual-frame = { workspace = true }
shrimply-manim-wgpu = { workspace = true }
tracing.workspace = true
wgpu = { workspace = true, features = ["vulkan"] }
