[package]
name = "shrimply-keyframe-graph-core"
version = "0.1.0"
edition = "2024"

[dependencies]
shrimply-discrete-keyframe-graph-core = { path = "../discrete-keyframe-graph-core" }
shrimply-cross-ui-theme = { path = "../../ui/cross-ui-theme" }
shrimply-interpolation = { path = "../../interpolation" }
shrimply-math-core = { path = "../../math/core" }
shrimply-math-color = { path = "../../math/color" }
shrimply-math-geometry = { path = "../../math/geometry" }
glam.workspace = true
skia-safe = { workspace = true, features = ["gl", "textlayout"] }
shrimply-skia-adw-core = { path = "../../ui/skia-adw-core" }
uuid = { workspace = true, features = ["v4", "serde"] }
