[package]
name = "shrimply-preview-gtk"
version = "0.1.0"
edition = "2024"

[dependencies]
adw.workspace = true
shrimply-cuda.workspace = true
glam.workspace = true
glow.workspace = true
gtk.workspace = true
libc.workspace = true
shrimply-audio = { path = "../../audio/audio" }
shrimply-benchmarking = { path = "../../benchmarking" }
shrimply-core = { path = "../../core" }
shrimply-math-core = { path = "../../math/core" }
shrimply-evaluation = { path = "../../evaluation" }
shrimply-gpu-memory = { path = "../../video/gpu-memory" }
shrimply-paint-edit = { path = "../../paint/paint-edit" }
shrimply-project = { path = "../../project/project" }
shrimply-preview-core = { path = "../preview-core" }
shrimply-preview-runtime = { path = "../preview-runtime" }
shrimply-playback-performance = { path = "../playback-performance" }
shrimply-render-core = { path = "../../render-core" }
shrimply-skia-adw-core = { path = "../../ui/skia-adw-core" }
shrimply-state = { path = "../../state" }
shrimply-timeline = { path = "../../timeline/timeline" }
shrimply-gtk-components = { path = "../../ui/gtk-components" }
shrimply-video = { path = "../../video/rendering" }
shrimply-video-modifiers = { path = "../../video/video-modifiers" }
shrimply-math-color = { path = "../../math/color", features = ["gdk"] }
skia-safe = { workspace = true, features = ["textlayout"] }
tracing.workspace = true
uuid = { workspace = true, features = ["v4"] }
