[package]
name = "shrimply-state"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown.workspace = true
shrimply-benchmarking = { path = "../benchmarking" }
shrimply-manim-core = { path = "../manim/manim-core" }
shrimply-math-core = { path = "../math/core" }
shrimply-preferences-core = { path = "../preferences/preferences-core" }
shrimply-project = { path = "../project/project" }
shrimply-preview-core = { path = "../preview/preview-core" }
shrimply-support = { path = "../support" }
tracing.workspace = true
uuid.workspace = true
