[package]
name = "shrimply-qt-components-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib = { workspace = true, features = ["qt_full"] }
shrimply-benchmarking = { path = "../../benchmarking" }
shrimply-components-demo-core = { path = "../components-demo-core" }
shrimply-keyframe-graph-core = { path = "../../timeline/keyframe-graph-core" }
shrimply-math-core = { path = "../../math/core" }
shrimply-qt-components = { path = "../qt-components" }
shrimply-qt-helpers = { path = "../qt-helpers" }
shrimply-support = { path = "../../support" }

[build-dependencies]
cxx-qt-build = { workspace = true, features = ["link_qt_object_files"] }
