[package]
name = "shrimply-inspector-gtk"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown.workspace = true
adw.workspace = true
async-channel.workspace = true
ffmpeg-next.workspace = true
glam.workspace = true
gtk.workspace = true
num-traits.workspace = true
pango = { workspace = true, features = ["v1_56"] }
serde_json.workspace = true
shrimply-audio = { path = "../../audio/audio" }
shrimply-audio-modifiers = { path = "../../audio/audio-modifiers" }
shrimply-benchmarking = { path = "../../benchmarking" }
shrimply-3dgs = { path = "../../3d/3dgs" }
shrimply-core = { path = "../../core" }
shrimply-component-core = { path = "../component-core" }
shrimply-evaluation = { path = "../../evaluation" }
shrimply-discrete-keyframe-graph-core = { path = "../../timeline/discrete-keyframe-graph-core" }
shrimply-interpolation = { path = "../../interpolation" }
shrimply-inspector-core = { path = "../inspector-core" }
shrimply-media-info = { path = "../../media-info" }
shrimply-property-transfer = { path = "../../property-transfer" }
shrimply-project = { path = "../../project/project" }
shrimply-resource-pipeline = { path = "../../resource-pipeline" }
shrimply-text-3d = { path = "../../3d/text-3d" }
shrimply-render-core = { path = "../../render-core" }
shrimply-scene-3d = { path = "../../3d/scene-3d" }
shrimply-server-client = { path = "../../server-client" }
shrimply-shape-3d = { path = "../../3d/shape-3d" }
shrimply-state = { path = "../../state" }
shrimply-tts = { path = "../../audio/tts" }
shrimply-tts-gtk = { path = "../../audio/tts-gtk" }
shrimply-support = { path = "../../support" }
shrimply-timeline = { path = "../../timeline/timeline" }
shrimply-gtk-components = { path = "../gtk-components" }
shrimply-video-modifiers = { path = "../../video/video-modifiers" }
shrimply-video-generation = { path = "../../video/video-generation" }
shrimply-video-generation-gtk = { path = "../../video/video-generation-gtk" }
shrimply-video-cuda = { path = "../../video/video-cuda" }
shrimply-math-color = { path = "../../math/color", features = ["gdk"] }
shrimply-cross-ui-theme = { path = "../cross-ui-theme" }
shrimply-math-geometry = { path = "../../math/geometry" }
shrimply-math-core = { path = "../../math/core" }
skia-safe = { workspace = true, features = ["gl", "textlayout"] }
shrimply-skia-adw-core = { path = "../skia-adw-core" }
sourceview5.workspace = true
tracing.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
