[package]
name = "shrimply-inspector-core"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel.workspace = true
ffmpeg-next.workspace = true
hashbrown.workspace = true
glam.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
shrimply-audio = { path = "../../audio/audio" }
shrimply-audio-modifiers = { path = "../../audio/audio-modifiers" }
shrimply-blender = { path = "../../blender/blender-bridge" }
shrimply-3dgs = { path = "../../3d/3dgs" }
shrimply-core = { path = "../../core" }
shrimply-evaluation = { path = "../../evaluation" }
shrimply-i18n-core = { path = "../i18n-core" }
shrimply-keyframe-graph-core = { path = "../../timeline/keyframe-graph-core" }
shrimply-manim-parser = { path = "../../manim/manim-parser" }
shrimply-math-core = { path = "../../math/core" }
shrimply-media-info = { path = "../../media-info" }
shrimply-pdf = { path = "../../pdf" }
shrimply-property-transfer = { path = "../../property-transfer" }
shrimply-preview-core = { path = "../../preview/preview-core" }
shrimply-project = { path = "../../project/project" }
shrimply-server-client = { path = "../../server-client" }
shrimply-scene-3d = { path = "../../3d/scene-3d" }
shrimply-shape-3d = { path = "../../3d/shape-3d" }
shrimply-state = { path = "../../state" }
shrimply-text-3d = { path = "../../3d/text-3d" }
shrimply-timeline = { path = "../../timeline/timeline" }
shrimply-tts = { path = "../../audio/tts" }
shrimply-video = { path = "../../video/rendering" }
shrimply-video-modifiers = { path = "../../video/video-modifiers" }
skia-safe = { workspace = true, features = ["textlayout"] }
strum.workspace = true
tempfile.workspace = true
tracing.workspace = true
uuid = { workspace = true, features = ["v4"] }
