[package]
name = "shrimply-render-core"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
autodiff.workspace = true
glam.workspace = true
nalgebra.workspace = true
num-traits.workspace = true
serde = { workspace = true, features = ["derive"] }
shrimply-math-color = { workspace = true }
shrimply-math-geometry = { workspace = true }

[features]
cuda = ["dep:shrimply-gpu-cuda"]

[target.'cfg(any(target_os = "linux", windows))'.dependencies]
shrimply-gpu-cuda = { workspace = true, optional = true }

[build-dependencies]
serde_json.workspace = true
shrimply-slang-build = { workspace = true }
