[package]
name = "shrimply-audio-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown.workspace = true
cached.workspace = true
cpal.workspace = true
deep_filter.workspace = true
easyfft.workspace = true
ffmpeg-next.workspace = true
glam.workspace = true
fundsp = { workspace = true, features = ["std"] }
libc.workspace = true
ndarray.workspace = true
nnnoiseless.workspace = true
rayon.workspace = true
rusqlite = { workspace = true, features = ["bundled"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
shrimply-audio-modifiers = { workspace = true }
shrimply-asset = { workspace = true }
shrimply-profiling = { workspace = true }
shrimply-property-model = { workspace = true }
shrimply-lip-sync = { workspace = true }
shrimply-math-media = { workspace = true }
shrimply-math-core = { workspace = true }
shrimply-path-core.workspace = true
shrimply-project-document = { workspace = true, default-features = true }
shrimply-resource-pipeline = { workspace = true }
shrimply-compute-client = { workspace = true }
tempfile.workspace = true
tracing.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
