[package]
name = "shrimply-preview-provider-skia"
version = "0.1.0"
edition = "2024"

[dependencies]
glam.workspace = true
shrimply-math-color = { workspace = true, features = ["skia"] }
shrimply-math-geometry = { workspace = true }
shrimply-math-core = { workspace = true }
shrimply-drawing-skia = { workspace = true }
shrimply-timeline-value = { workspace = true }
uuid.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
skia-safe = { workspace = true, features = ["all-linux"] }

[target.'cfg(target_os = "macos")'.dependencies]
skia-safe = { workspace = true, features = ["all-macos"] }

[target.'cfg(windows)'.dependencies]
skia-safe = { workspace = true, features = ["all-windows"] }
