[package]
name = "shrimply-preview-interaction-skia"
version = "0.1.0"
edition = "2024"

[dependencies]
shrimply-process-reporting.workspace = true
glam.workspace = true
skia-safe = { workspace = true, features = ["textlayout"] }
uuid.workspace = true
shrimply-property-model = { workspace = true }
shrimply-project-evaluation = { workspace = true }
shrimply-visual-core = { workspace = true }
shrimply-3dgs-core = { workspace = true }
shrimply-preview-provider-skia = { workspace = true }
shrimply-project-document = { workspace = true, default-features = true }
shrimply-math-color = { workspace = true, features = ["skia"] }
shrimply-components-skia = { workspace = true }
shrimply-cross-ui-theme = { workspace = true }
