[package]
name = "shrimply-trust-core"
version = "0.1.0"
edition = "2024"

[dependencies]
libc.workspace = true
rusqlite = { workspace = true, features = ["bundled"] }
shrimply-path-core.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_Foundation", "Win32_Security", "Win32_System_JobObjects", "Win32_System_Threading"] }
