[package]
name = "shrimply-timeline-core"
version = "0.1.0"
edition = "2024"

[dependencies]
ffmpeg-next.workspace = true
glam.workspace = true
hashbrown.workspace = true
shrimply-3dgs = { path = "../../3d/3dgs" }
shrimply-blender = { path = "../../blender/blender-bridge" }
shrimply-core = { path = "../../core" }
shrimply-math-core = { path = "../../math/core" }
shrimply-pdf = { path = "../../pdf" }
shrimply-project = { path = "../../project/project" }
shrimply-resource-pipeline = { path = "../../resource-pipeline" }
shrimply-scene-3d = { path = "../../3d/scene-3d" }
shrimply-state = { path = "../../state" }
shrimply-timeline = { path = "../timeline" }
shrimply-video = { path = "../../video/rendering" }
shrimply-video-modifiers = { path = "../../video/video-modifiers" }
uuid = { workspace = true, features = ["v4"] }
