[package]
name = "shrimply-components-qt"
version = "0.1.0"
edition = "2024"

[dependencies]
shrimply-surface-gl-skia = { workspace = true }
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib = { workspace = true, features = ["qt_full"] }
shrimply-components-core = { workspace = true }
shrimply-cross-ui-core = { workspace = true }
shrimply-cross-ui-theme = { workspace = true }
shrimply-i18n-qt = { workspace = true }
shrimply-math-interpolation = { workspace = true }
shrimply-keyframe-graph-skia = { workspace = true }
shrimply-math-color = { workspace = true }
shrimply-math-core = { workspace = true }
shrimply-project-types = { workspace = true }
shrimply-application-qt = { workspace = true }
shrimply-components-skia = { workspace = true }
shrimply-process-reporting = { workspace = true }
uuid.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
shrimply-pointer-lock-wayland = { workspace = true }

[build-dependencies]
cxx-qt-build = { workspace = true, features = ["link_qt_object_files"] }
