[package]
name = "shrimply-launcher-qt"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "shrimply-qt"
path = "src/main.rs"

[dependencies]
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib = { workspace = true, features = ["qt_full"] }
shrimply-cross-ui-core = { path = "../../ui/cross-ui-core" }
shrimply-i18n-qt = { path = "../../ui/i18n-qt" }
shrimply-qt-helpers = { path = "../../ui/qt-helpers" }
shrimply-support = { path = "../../support" }
tracing.workspace = true

[build-dependencies]
cxx-qt-build = { workspace = true, features = ["link_qt_object_files"] }
