[package]
name = "shrimply-ui-foundation"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel.workspace = true
hashbrown.workspace = true
adw.workspace = true
cached.workspace = true
glow.workspace = true
gtk.workspace = true
num-traits.workspace = true
shrimply-project-core = { path = "../../project/project-core" }
shrimply-resource-pipeline = { path = "../../resource-pipeline" }
shrimply-math-color = { path = "../../math/color", features = ["gdk", "skia"] }
shrimply-math-core = { path = "../../math/core" }
shrimply-math-geometry = { path = "../../math/geometry", features = ["skia"] }
shrimply-i18n = { path = "../i18n" }
skia-safe = { workspace = true, features = ["gl", "vulkan", "textlayout"] }
sourceview5.workspace = true
strum.workspace = true
tracing.workspace = true
typos.workspace = true
typos-dict.workspace = true
unicase.workspace = true

[target.'cfg(not(target_os = "linux"))'.dependencies]
libc.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
wayland-client = { workspace = true, features = ["system"] }
wayland-protocols = { workspace = true, features = ["client", "unstable"] }
