[package]
name = "shrimply-video"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
hashbrown.workspace = true
ash.workspace = true
cached.workspace = true
cairo = { workspace = true, features = ["freetype"] }
shrimply-cuda.workspace = true
ffmpeg-next.workspace = true
glam.workspace = true
glib.workspace = true
libc.workspace = true
num-traits.workspace = true
pango = { workspace = true, features = ["v1_57"] }
pangocairo.workspace = true
png.workspace = true
rayon.workspace = true
rusqlite = { workspace = true, features = ["bundled"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
shrimply-core = { path = "../../core" }
shrimply-asset = { path = "../../asset" }
shrimply-3dgs = { path = "../../3d/3dgs" }
shrimply-audio = { path = "../../audio/audio" }
shrimply-anime4k = { path = "../anime4k" }
shrimply-affine-l1-stabilization = { path = "../../stabilization/affine-l1-stabilization" }
shrimply-benchmarking = { path = "../../benchmarking" }
shrimply-blender = { path = "../../blender/blender-bridge" }
shrimply-background = { path = "../../background" }
shrimply-evaluation = { path = "../../evaluation" }
shrimply-gpu-memory = { path = "../gpu-memory" }
shrimply-i18n-core = { path = "../../ui/i18n-core" }
shrimply-visual-frame = { path = "../visual-frame" }
shrimply-layered-image = { path = "../../layered-image/layered-image" }
shrimply-loading-screen = { path = "../../preview/loading-screen" }
shrimply-math-media = { path = "../../math/media" }
shrimply-math-core = { path = "../../math/core" }
shrimply-math-color = { path = "../../math/color", features = ["cuda", "skia"] }
shrimply-math-geometry = { path = "../../math/geometry", features = ["skia"] }
shrimply-manim-parser = { path = "../../manim/manim-parser" }
shrimply-manim-wgpu = { path = "../../manim/manim-wgpu" }
shrimply-mesh-flow-stabilization = { path = "../../stabilization/mesh-flow-stabilization" }
shrimply-nvidia-optical-flow = { path = "../../stabilization/nvidia-optical-flow" }
shrimply-optix-denoiser = { path = "../../3d/optix-denoiser" }
shrimply-paint-skia = { path = "../../paint/paint-skia" }
shrimply-pdf = { path = "../../pdf" }
shrimply-preview-skia = { path = "../../preview/preview-skia" }
shrimply-project = { path = "../../project/project" }
shrimply-render-core = { path = "../../render-core", features = ["cuda"] }
shrimply-render-3d = { path = "../../3d/render-3d" }
shrimply-resource-pipeline = { path = "../../resource-pipeline" }
shrimply-scene-3d = { path = "../../3d/scene-3d" }
shrimply-shape-3d = { path = "../../3d/shape-3d" }
shrimply-text-3d = { path = "../../3d/text-3d" }
shrimply-video-modifiers = { path = "../video-modifiers" }
shrimply-video-decoder = { path = "../decoder" }
shrimply-server-client = { path = "../../server-client" }
skia-safe = { workspace = true, features = ["gl", "vulkan", "textlayout", "svg"] }
tempfile.workspace = true
tracing.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
vtracer.workspace = true
shrimply-transform-3d = { path = "../../3d/transform-3d" }

[build-dependencies]
serde_json.workspace = true
shrimply-slang-build = { path = "../../slang-build" }
