[package]
name = "shrimply-timeline-gtk"
version = "0.1.0"
edition = "2024"

[dependencies]
shrimply-skia-gl = { path = "../../ui/skia-gl" }
async-channel.workspace = true
hashbrown.workspace = true
adw.workspace = true
ffmpeg-next.workspace = true
glam.workspace = true
gtk.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
shrimply-audio = { path = "../../audio/audio" }
shrimply-core = { path = "../../core" }
shrimply-timeline-core = { path = "../timeline-core" }
shrimply-cross-ui-theme = { path = "../../ui/cross-ui-theme" }
shrimply-export-core = { path = "../../export/export-core" }
shrimply-math-media = { path = "../../math/media" }
shrimply-math-core = { path = "../../math/core" }
shrimply-property-transfer = { path = "../../property-transfer" }
shrimply-project = { path = "../../project/project" }
shrimply-playback-performance = { path = "../../preview/playback-performance" }
shrimply-resource-pipeline = { path = "../../resource-pipeline" }
shrimply-server-client = { path = "../../server-client" }
shrimply-state = { path = "../../state" }
shrimply-support = { path = "../../support" }
shrimply-timeline = { path = "../timeline" }
shrimply-timeline-snap = { path = "../timeline-snap" }
shrimply-transcription = { path = "../../audio/transcription" }
shrimply-tts = { path = "../../audio/tts" }
shrimply-tts-gtk = { path = "../../audio/tts-gtk" }
shrimply-gtk-components = { path = "../../ui/gtk-components" }
shrimply-inspector-core = { path = "../../ui/inspector-core" }
shrimply-wayland-pointer-lock = { path = "../../ui/wayland-pointer-lock" }
shrimply-video = { path = "../../video/rendering" }
shrimply-video-recording = { path = "../../video/video-recording" }
shrimply-video-modifiers = { path = "../../video/video-modifiers" }
shrimply-math-color = { path = "../../math/color", features = ["gdk"] }
shrimply-skia-adw-core = { path = "../../ui/skia-adw-core" }
skia-safe = { workspace = true, features = ["gl", "textlayout"] }
tracing.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
