[package]
name = "shrimply-manim-bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
shrimply-trust-core.workspace = true
cached = { workspace = true, features = ["proc_macro"] }
hashbrown.workspace = true
libc.workspace = true
rmp-serde.workspace = true
serde = { workspace = true, features = ["derive"] }
shrimply-asset = { workspace = true }
shrimply-manim-ir = { workspace = true }
shrimply-math-core = { workspace = true }
shrimply-project-document = { workspace = true, default-features = true }
tracing.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-foundation.workspace = true
