[package]
name = "shrimply-preview-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
shrimply-skia-gl = { path = "../../ui/skia-gl" }
shrimply-cuda.workspace = true
glam.workspace = true
glow.workspace = true
libc.workspace = true
shrimply-audio = { path = "../../audio/audio" }
shrimply-cross-ui-theme = { path = "../../ui/cross-ui-theme" }
shrimply-core = { path = "../../core" }
shrimply-evaluation = { path = "../../evaluation" }
shrimply-gpu-memory = { path = "../../video/gpu-memory" }
shrimply-math-color = { path = "../../math/color", features = ["skia"] }
shrimply-math-core = { path = "../../math/core" }
shrimply-playback-performance = { path = "../playback-performance" }
shrimply-project = { path = "../../project/project" }
shrimply-preview-core = { path = "../preview-core" }
shrimply-skia-adw-core = { path = "../../ui/skia-adw-core" }
shrimply-state = { path = "../../state" }
shrimply-video = { path = "../../video/rendering" }
skia-safe = { workspace = true, features = ["textlayout"] }
tracing.workspace = true
uuid = { workspace = true, features = ["v4"] }
