[package]
name = "shrimply-video-generation-gtk"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel.workspace = true
gtk.workspace = true
shrimply-math-core = { path = "../../math/core" }
shrimply-project = { path = "../../project/project" }
shrimply-server-client = { path = "../../server-client" }
shrimply-state = { path = "../../state" }
shrimply-gtk-components = { path = "../../ui/gtk-components" }
shrimply-video-generation = { path = "../video-generation" }
tracing.workspace = true
uuid = { workspace = true, features = ["v4"] }
