use std::{env, fs, path::PathBuf};

use serde_json::Value;

const SHADER_DIRECTORY: &str = "shaders";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../../slang-build/compiler.cpp");
    println!("cargo:rerun-if-changed=shaders");
    println!("cargo:rerun-if-env-changed=SLANG_SOURCE_DIR");
    println!("cargo:rerun-if-env-changed=SLANG_BUILD_DIR");

    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let shader_directory = manifest.join(SHADER_DIRECTORY);
    let shader_sources = shrimply_slang_build::shader_sources(&shader_directory);
    for source in &shader_sources {
        println!("cargo:rerun-if-changed={}", source.display());
    }
    for source in shrimply_slang_build::shader_sources(&shader_directory.join("modules")) {
        println!("cargo:rerun-if-changed={}", source.display());
    }

    let output = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let compiler = shrimply_slang_build::Compiler::new(&shader_directory, &output);
    let mut bindings = String::from("// @generated by render-3d/build.rs from Slang reflection.\n");
    for source in shader_sources {
        let module = source
            .file_stem()
            .and_then(|name| name.to_str())
            .expect("Slang module filename must be UTF-8");
        let artifacts = compiler.compile(&source, shrimply_slang_build::Target::Spirv, &[]);
        let reflected: Value = serde_json::from_slice(&artifacts.reflection)
            .unwrap_or_else(|error| panic!("parse Slang reflection for {module}: {error}"));
        bindings.push_str(&shrimply_slang_build::generate_module(
            module,
            &artifacts.filename,
            &reflected,
            &artifacts.abi,
        ));
    }
    fs::write(output.join("slang_bindings.rs"), bindings)
        .expect("write reflected Slang Rust bindings");
}
