[package]
name = "shrimply-timeline-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel.workspace = true
hashbrown.workspace = true
adw.workspace = true
ffmpeg-next.workspace = true
glam.workspace = true
gtk.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
shrimply-3dgs = { path = "../../3d/3dgs" }
shrimply-audio = { path = "../../audio/audio" }
shrimply-blender = { path = "../../blender/blender-bridge" }
shrimply-core = { path = "../../core" }
shrimply-export = { path = "../../export/export" }
shrimply-math-media = { path = "../../math/media" }
shrimply-math-core = { path = "../../math/core" }
shrimply-property-transfer = { path = "../../property-transfer" }
shrimply-project = { path = "../../project/project" }
shrimply-playback-performance = { path = "../../preview/playback-performance" }
shrimply-pdf = { path = "../../pdf" }
shrimply-scene-3d = { path = "../../3d/scene-3d" }
shrimply-resource-pipeline = { path = "../../resource-pipeline" }
shrimply-server-client = { path = "../../server-client" }
shrimply-state = { path = "../../state" }
shrimply-support = { path = "../../support" }
shrimply-timeline = { path = "../timeline" }
shrimply-timeline-snap = { path = "../timeline-snap" }
shrimply-transcription = { path = "../../audio/transcription" }
shrimply-tts = { path = "../../audio/tts" }
shrimply-tts-ui = { path = "../../audio/tts-ui" }
shrimply-ui-foundation = { path = "../../ui/ui-foundation" }
shrimply-video = { path = "../../video/rendering" }
shrimply-video-recording = { path = "../../video/video-recording", optional = true }
shrimply-video-modifiers = { path = "../../video/video-modifiers" }
shrimply-math-color = { path = "../../math/color", features = ["gdk"] }
shrimply-skia-adw-ui = { path = "../../ui/skia-adw-ui" }
skia-safe = { workspace = true, features = ["gl", "textlayout"] }
tracing.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }

[features]
screen-recording = ["dep:shrimply-video-recording"]
