[package]
name = "shrimply-preview-qt"
version = "0.1.0"
edition = "2024"

[dependencies]
shrimply-surface-gl-skia = { workspace = true }
glam.workspace = true
shrimply-audio-engine = { workspace = true }
shrimply-cross-ui-core = { workspace = true }
shrimply-cross-ui-theme = { workspace = true }
shrimply-project-evaluation = { workspace = true }
shrimply-timeline-qt = { workspace = true }
shrimply-timeline-edit = { workspace = true }
shrimply-math-color = { workspace = true }
shrimply-playback-performance = { workspace = true }
shrimply-paint-edit-skia = { workspace = true }
shrimply-preview-provider-skia = { workspace = true }
shrimply-preview-runtime-cuda = { workspace = true }
shrimply-project-document = { workspace = true, default-features = true }
shrimply-components-skia = { workspace = true }
shrimply-editor-state = { workspace = true }
shrimply-visual-cuda = { workspace = true }
skia-safe.workspace = true
tracing.workspace = true
uuid.workspace = true
