[package]
name = "shrimply-editor-qt"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "shrimply-editor-qt"
path = "src/main.rs"

[dependencies]
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib = { workspace = true, features = ["qt_full"] }
ffmpeg-next.workspace = true
shrimply-cross-ui-core = { path = "../../ui/cross-ui-core" }
shrimply-export-qt = { path = "../../export/export-qt" }
shrimply-i18n-qt = { path = "../../ui/i18n-qt" }
shrimply-inspector-qt = { path = "../../ui/inspector-qt" }
shrimply-math-core = { path = "../../math/core" }
shrimply-preview-qt = { path = "../../preview/preview-qt" }
shrimply-preview-runtime = { path = "../../preview/preview-runtime" }
shrimply-preferences-qt = { path = "../../preferences/preferences-qt" }
shrimply-project = { path = "../../project/project" }
shrimply-qt-helpers = { path = "../../ui/qt-helpers" }
shrimply-qt-components = { path = "../../ui/qt-components" }
shrimply-state = { path = "../../state" }
shrimply-support = { path = "../../support" }
tracing.workspace = true

[build-dependencies]
cxx-qt-build = { workspace = true, features = ["link_qt_object_files"] }
