[package]
name = "shrimply-playback-performance"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel.workspace = true
rangemap.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
shrimply-math-core = { path = "../../math/core" }
shrimply-math-media = { path = "../../math/media" }
shrimply-project = { path = "../../project/project" }
shrimply-preview-core = { path = "../preview-core" }
tracing.workspace = true
uuid.workspace = true
