[package]
name = "shrimply-preview-qt"
version = "0.1.0"
edition = "2024"

[dependencies]
shrimply-skia-gl = { path = "../../ui/skia-gl" }
glam.workspace = true
shrimply-audio = { path = "../../audio/audio" }
shrimply-cross-ui-core = { path = "../../ui/cross-ui-core" }
shrimply-cross-ui-theme = { path = "../../ui/cross-ui-theme" }
shrimply-evaluation = { path = "../../evaluation" }
shrimply-timeline-qt = { path = "../../timeline/timeline-qt" }
shrimply-timeline = { path = "../../timeline/timeline" }
shrimply-math-color = { path = "../../math/color" }
shrimply-playback-performance = { path = "../playback-performance" }
shrimply-paint-edit = { path = "../../paint/paint-edit" }
shrimply-preview-core = { path = "../preview-core" }
shrimply-preview-runtime = { path = "../preview-runtime" }
shrimply-project = { path = "../../project/project" }
shrimply-skia-adw-core = { path = "../../ui/skia-adw-core" }
shrimply-state = { path = "../../state" }
shrimply-timeline-gtk = { path = "../../timeline/timeline-gtk" }
shrimply-video = { path = "../../video/rendering" }
skia-safe.workspace = true
tracing.workspace = true
uuid.workspace = true
