[package]
name = "shrimply-components-gtk"
version = "0.1.0"
edition = "2024"

[dependencies]
shrimply-trust-core.workspace = true
shrimply-surface-gl-skia = { workspace = true }
async-channel.workspace = true
hashbrown.workspace = true
adw.workspace = true
cached.workspace = true
glow.workspace = true
gtk.workspace = true
num-traits.workspace = true
shrimply-project-types = { workspace = true }
shrimply-components-core = { workspace = true }
shrimply-cross-ui-core = { workspace = true }
shrimply-cross-ui-theme = { workspace = true }
shrimply-framegraph-skia = { workspace = true }
shrimply-resource-pipeline = { workspace = true }
shrimply-math-color = { workspace = true, features = ["gdk", "skia"] }
shrimply-math-core = { workspace = true }
shrimply-math-geometry = { workspace = true, features = ["skia"] }
shrimply-components-skia = { workspace = true }
shrimply-pointer-lock-wayland = { workspace = true }
shrimply-i18n = { workspace = true }
shrimply-math-interpolation = { workspace = true }
shrimply-keyframe-graph-skia = { workspace = true }
skia-safe = { workspace = true, features = ["gl", "vulkan", "textlayout"] }
sourceview5.workspace = true
strum.workspace = true
tracing.workspace = true
uuid.workspace = true
