[package]
name = "shrimply-timeline-skia"
version = "0.1.0"
edition = "2024"

[dependencies]
shrimply-trust-core.workspace = true
async-channel.workspace = true
serde_json.workspace = true
shrimply-process-reporting = { workspace = true }
ffmpeg-next.workspace = true
glam.workspace = true
hashbrown.workspace = true
imagesize.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
shrimply-3dgs-core = { workspace = true }
shrimply-blender-core = { workspace = true }
shrimply-property-model = { workspace = true }
shrimply-math-core = { workspace = true }
shrimply-pdf = { workspace = true }
shrimply-project-document = { workspace = true, default-features = true }
shrimply-property-transfer = { workspace = true }
shrimply-resource-pipeline = { workspace = true }
shrimply-compute-client = { workspace = true }
shrimply-scene-3d = { workspace = true }
shrimply-editor-state = { workspace = true }
shrimply-timeline-edit = { workspace = true }
shrimply-transcription = { workspace = true }
shrimply-tts = { workspace = true }
shrimply-layered-image-loader = { workspace = true }
shrimply-visual-modifiers = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
shrimply-audio-engine = { workspace = true }
shrimply-math-media = { workspace = true }
shrimply-math-color = { workspace = true }
shrimply-playback-performance = { workspace = true }
shrimply-components-skia = { workspace = true }
shrimply-cross-ui-theme = { workspace = true }
shrimply-i18n = { workspace = true }
tracing.workspace = true
skia-safe.workspace = true
shrimply-timeline-snap = { workspace = true }
