[package]
name = "shrimply-manim-wgpu"
version = "0.1.0"
edition = "2024"
build = false

[dependencies]
hashbrown.workspace = true
pollster = "1"
shrimply-asset = { path = "../../asset" }
shrimply-i18n-core = { path = "../../ui/i18n-core" }
shrimply-loading-screen = { path = "../../preview/loading-screen" }
shrimply-manim-core = { path = "../manim-core" }
shrimply-manim-ir = { path = "../manim-ir" }
shrimply-manim-parser = { path = "../manim-parser" }
shrimply-math-color = { path = "../../math/color" }
shrimply-math-core = { path = "../../math/core" }
shrimply-project = { path = "../../project/project" }
tracing.workspace = true
uuid.workspace = true
wgpu.workspace = true

[dev-dependencies]
ffmpeg-next.workspace = true
tempfile.workspace = true

[target.'cfg(target_os = "macos")'.dev-dependencies]
wgpu = { workspace = true, features = ["metal"] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
wgpu = { workspace = true, features = ["vulkan"] }
