[package]
name = "shrimply-preferences-gtk"
version = "0.1.0"
edition = "2024"

[dependencies]
shrimply-trust-core.workspace = true
adw.workspace = true
async-channel.workspace = true
gtk.workspace = true
pango.workspace = true
shrimply-blender-core = { workspace = true }
shrimply-inspector-gtk = { workspace = true }
shrimply-preferences-core = { workspace = true }
shrimply-components-gtk = { workspace = true }
