[package]
name = "shrimply-render-core"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
autodiff.workspace = true
glam.workspace = true
nalgebra.workspace = true
num-traits.workspace = true
serde = { workspace = true, features = ["derive"] }
shrimply-math-color = { path = "../math/color" }
shrimply-math-geometry = { path = "../math/geometry" }

[features]
cuda = ["dep:shrimply-cuda"]

[target.'cfg(target_os = "linux")'.dependencies]
shrimply-cuda = { workspace = true, optional = true }

[build-dependencies]
serde_json.workspace = true
shrimply-slang-build = { path = "../slang-build" }
