[package]
name = "shrimply-components-demo-core"
version = "0.1.0"
edition = "2024"

[dependencies]
rhai.workspace = true
shrimply-core = { path = "../../core" }
shrimply-interpolation = { path = "../../interpolation" }
shrimply-keyframe-graph-core = { path = "../../timeline/keyframe-graph-core" }
shrimply-math-core = { path = "../../math/core" }
shrimply-video-modifiers = { path = "../../video/video-modifiers" }
uuid.workspace = true
