[package]
name = "shrimply-framegraph-appkit"
version = "0.1.0"
edition = "2024"

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-app-kit.workspace = true
objc2-foundation.workspace = true
objc2-quartz-core.workspace = true
shrimply-cross-ui-theme = { workspace = true }
shrimply-framegraph-skia = { workspace = true }
shrimply-keyframe-graph-skia = { workspace = true }
shrimply-math-core = { workspace = true }
shrimply-components-skia = { workspace = true }
shrimply-surface-metal-skia = { workspace = true }
