[package]
name = "shrimply-launcher-gtk"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "shrimply"
path = "src/main.rs"

[dependencies]
adw.workspace = true
gtk.workspace = true
shrimply-cross-ui-core = { path = "../../ui/cross-ui-core" }
shrimply-support = { path = "../../support" }
shrimply-project = { path = "../../project/project" }
shrimply-gtk-components = { path = "../../ui/gtk-components" }
tracing.workspace = true
